[build]
    publish     = "client/dist"
    functions   = "netlify/functions"
    command     = "cd client && npm run build"

[dev]
    autoLaunch=true
    port        = 8989

[functions]
    [functions.app]
        included_files = ["client/dist/index.html"]

[[redirects]]
    from        = "/"
    to          = "/.netlify/functions/app"
    status      = 200
    force       = true

    # force = true set in redirect to send all requests to your function even if content is found.
    # As my root directory (public) has a index.html file, this file is served first without the 'force'
    # setting to true.